### ISSUE TITLE
Spleef

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#11]
**Minecraft username**: AwesomelyEpic1

**Applicable Realm – Skyblock or Minigames**: Minigames

**Your Idea**: Its just like it sounds, a spleef game. could do a single mass game or a tournament. Everyone gets a "god" type shovel and the floor is made of snow. If the block under you gets mined and you fall you are out, last man standing wins. No time limit as more of the floor is destroyed there is less area to maneuver and eventually there will only be on man left. If there is no body left and the last two people fall its a draw (highly unlikely this happens).

**Comment by joshwenke** [comment]
We will definitely have spleef! :)

**Comment by Treellane** [comment]
A time limit may be needed! ... What is the remaining player can not get to each other because the 'floor' in between them is gone? Players won't be able to get down to the last man standing and the game will go on forever! A time limit, or another way around this issue is needed, other then that, it sounds fun.
