### ISSUE TITLE
Everyone wants this!

### ISSUE THREAD

**Issue by GalaxyRR** [CobaltMC/cobalt-issues#47]
GalaxyRR
Everyone wants it!
To not be **banned** for actualy stupid things. Like...taking **YOUR** stuff to another place and gets count as a **GRIEF** and then appealing for it and **admiting** it as you **DID** grief. And after all **GETTING A BAN RECORD FOR IT!**
No one wants to be banned like that.

**Comment by joshwenke** [comment]
You should be thankful you weren’t permanently banned, which would have happened if we didn’t have the confirm-ban system. If you’d like me to skip the c-ban for this infraction and change it to a full ban, let me know. Otherwise, consider this a warning (exactly what c-bans are) and make sure you don’t break any rules in the future. 

And don’t use our GitHub to complain. This is for feature requests and bug reports.
